### ISSUE TITLE
keyboard problem on Mac OS X

### ISSUE THREAD

**Issue by fuhrthom** [DomenicDev/Bomberman#29]
If I go straight on a wall, at some reason the player doens't walk anymore. But the KI walks without problems. I have to restart the game. 
The player walks since I walk into a wall or block, then he bugs and can't walk anymore.

**Comment by DomenicDev** [comment]
Okay, we will investigate this in phase 3!
Thanks for the report!

**Comment by DomenicDev** [comment]
We switched to arrow keys with the latest commits. This seems to fix this issue.
